### ISSUE TITLE
Question about migrating?

### ISSUE THREAD

**Issue by farzadha2** [gurucomputing/meshcentral-docker#3]
Hi
I was wondering if someone could shed somelight, im currently have the meshcentral on a vm and want to migrate to docker

i have a copy of the server meshcentral-autobackup-2022-07-12-20-45.zip
which has the meshcentral data and the mongodump

would copy the files of the meshcentral data to my other hosts which has the docker of meshcentral? and how would i restore the mongodb?

i know i would need to change my config.json maybe something like this?

```
{
  "__comment__" : "This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "settings": {
  "Cert": "remote.domain.com",
  "trustedproxy": "CloudFlare",
    "mongoDb": "mongodb://meshcentral-db:27017",
    "mongoDbName": "meshcentral",
    "dbEncryptKey": "mysecretpassword"
    "WANonly": true,
    "Port": 4430,
    "RedirPort": 800,
    "AliasPort": 443,
    "MeshErrorLogPath": "/var/log/mesh.log",
    "NpmPath": "/usr/bin/node /usr/bin/npm",
    "TlsOffload": "127.0.0.1",
    "BrowserPong": 20,
    "AgentPong": 20,
    "AutoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 10,
      "backupPath": "/root/meshcentral-backup"
    },
  },
  "domains": {
    "": {
      "Title": "Mesh central ",
      "Title2": "Remote",
      "TitlePicture": "pic.png",
      "WelcomePicture": "pic2.png",
      "WelcomePictureFullScreen": true,
      "CertUrl": "https://remote.domain.com:443/",
      "agentCustomization": {
          "displayName": "meshcentral",
          "description": "Remote",
          "companyName": "remote",
          "serviceName": "agent",
          "filenameName": "agent",
          "image": "agent.png",
          "installText": "Remote"
          },
    },

  },
}
```
docker compose

```

version: '2'
# This is example 2 from the documentation
services:
  meshcentral:
    container_name: meshcentral
    image: ghcr.io/gurucomputing/meshcentral-docker:latest
    restart: "always"
    volumes:
      - ./container-data/meshcentral-data:/meshcentral/meshcentral-data
      - ./container-data/meshcentral-files:/meshcentral/meshcentral-files
      - ./container-data/meshcentral-backup:/meshcentral/meshcentral-backup
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGODB_URL=mongodb://meshcentral-db:27017
      - MONGODB_NAME=meshcentral
      - DB_ENCRYPT_KEY=mysecretpassword
    ports:
      - 800:80
      - 4430:443
    networks:
      - meshcentral-nw
  meshcentral-db:
    container_name: meshcentral-db
    image: mongo:4.4.6
    restart: "always"
    volumes:
      - ./container-data/db:/data/db
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 27017:27017
    networks:
      - meshcentral-nw

networks:
  meshcentral-nw:
```

Thank you
