### ISSUE TITLE
issue on installing with config

### ISSUE THREAD

**Issue by killmasta93** [gurucomputing/meshcentral-docker#5]
Hi @routerino currently trying to copy a config i had on a previous vm with meshcentral but im getting this error 

`ERROR: Unable to parse /meshcentral/meshcentral-data/config.json`

i was also trying to publish the port 8085 to use http only has im going to use my SWAG docker which has reverse proxy but cant seem to get it use http 

this is the config
```

{
  "__comment__" : "This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "settings": {
    "Cert": "remoto.domain.com",
    "mongoDb": "mongodb://meshcentral-db:27017",
    "mongoDbName": "meshcentral",
    "dbEncryptKey": "MyReallySecretPassword2"
    "WANonly": true,
    "Port": 8085,
    "AliasPort": 8085,
    "RedirPort": 8085,
    "AgentPing": 60,
    "AgentPong": 60,
    "NpmPath": "/usr/bin/node /usr/bin/npm",
    "TlsOffload": "127.0.0.1",
    "BrowserPong": 20,
    "ignoreagenthashcheck": false,
    },
 
    "domains": {
    "": {
      "Title": "Remoto",
      "Title2": "Remoto",
      "CertUrl": "https://remoto.domain.com:443/",
    },
  },
}
```
This is the docker-compose

```
version: '2'
# This is example 2 from the documentation
services:
  meshcentral:
    container_name: meshcentral
    image: ghcr.io/gurucomputing/meshcentral-docker:latest
    restart: "always"
    volumes:
      - meshcentral-data:/meshcentral/meshcentral-data
      - meshcentral-files:/meshcentral/meshcentral-files
      - meshcentral-backup:/meshcentral/meshcentral-backup
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGODB_URL=mongodb://meshcentral-db:27017
      - MONGODB_NAME=meshcentral
      - DB_ENCRYPT_KEY=${DB_ENCRYPT_KEY}
    ports:
      - 8085:80
      - 8086:443
    networks:
      - meshcentral-nw
  meshcentral-db:
    container_name: meshcentral-db
    image: mongo:3.6.3
    restart: "always"
    volumes:
      - mongo-data:/data/db
      - /etc/localtime:/etc/localtime:ro
    networks:
      - meshcentral-nw

networks:
  meshcentral-nw:

volumes:
  mongo-data:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/mongo-data
  meshcentral-data:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/meshcentral-data
  meshcentral-files:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/meshcentral-files
  meshcentral-backup:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/meshcentral-backup
```

Thank you
